version: '3.8'

services:
  noplacelike:
    build:
      context: .
      dockerfile: Dockerfile
    image: nathfavour/noplacelike:latest
    container_name: noplacelike-server
    restart: unless-stopped
    ports:
      - "8080:8080"  # Main HTTP port
      - "9090:9090"  # Metrics port
    volumes:
      - noplacelike-data:/home/noplacelike/data
      - noplacelike-uploads:/home/noplacelike/uploads
      - noplacelike-downloads:/home/noplacelike/downloads
      - noplacelike-plugins:/home/noplacelike/plugins
      - ./config:/config:ro
    environment:
      - NOPLACELIKE_HOST=0.0.0.0
      - NOPLACELIKE_PORT=8080
      - NOPLACELIKE_LOG_LEVEL=info
      - NOPLACELIKE_CONFIG=/config/production.json
    networks:
      - noplacelike-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: noplacelike-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - noplacelike-network
    depends_on:
      - noplacelike
    profiles:
      - monitoring

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: noplacelike-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - noplacelike-network
    depends_on:
      - prometheus
    profiles:
      - monitoring

  # Optional: Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: noplacelike-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - noplacelike-network
    profiles:
      - cache

volumes:
  noplacelike-data:
    driver: local
  noplacelike-uploads:
    driver: local
  noplacelike-downloads:
    driver: local
  noplacelike-plugins:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  redis-data:
    driver: local

networks:
  noplacelike-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16